return {
    -- {
    --     "nvim-neo-tree/neo-tree.nvim",
    --     branch = "v3.x",
    --     cmd = "Neotree",
    --     lazy = false, -- neo-tree will lazily load itself
    --     keys = {
    --         { "<leader>b", "<Cmd>Neotree<CR>", desc = "Toggle Neo-tree" },
    --     },
    --     dependencies = {
    --         "nvim-lua/plenary.nvim",
    --         "MunifTanjim/nui.nvim",
    --         "nvim-tree/nvim-web-devicons",
    --         "antosha417/nvim-lsp-file-operations",
    --     },
    --     opts = {
    --         close_if_last_window = true,
    --         filesystem = {
    --             follow_current_file = {
    --                 enabled = true,
    --             },
    --             use_libuv_file_watcher = true,
    --         },
    --     }
    -- },
}
